### ISSUE TITLE
bugs hide-and-seek

### ISSUE THREAD

**Issue by emmanuelsteven** [CaptainBawa/Portfolio#16]
this is preventing your index.js files from running,[https://github.com/CaptainBawa/Portfolio/blob/eca9e6885fbf52fc97b94a67e0005287f3cfd904/index.js#L2](https://github.com/CaptainBawa/Portfolio/blob/eca9e6885fbf52fc97b94a67e0005287f3cfd904/index.js#L2)

**Comment by CaptainBawa** [comment]
okay
